{{- if eq .Values.environment.type "CDK" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  IG_FQDN: obdemo.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: {{ .Values.environment.fr_platform.fqdn }}
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  ENVIRONMENT_TYPE: CDK
  # The fully qualified domain on which the remote consent server that is to be used to gain consent from the user 
  # will be available on. The ForgeRock platform must be configured to use this remote consent service.
  RCS_UI_FQDN: rcs-ui.{{ .Values.environment.sbat.domain }}
  AM_REALM: alpha
  USER_OBJECT: user
  IG_CLIENT_ID: ig-client
  IG_CLIENT_SECRET: password
  IG_IDM_USER: service_account.ig
  IG_IDM_PASSWORD: 0penBanking!
  IG_AGENT_ID: ig-agent
  IG_AGENT_PASSWORD: password
  IG_RCS_SECRET: password
  IG_SSA_SECRET: password
  CERT_ISSUER: null-issuer
  ASPSP_KEYSTORE_PATH: /secrets/aspsp.test.p12
  ASPSP_KEYSTORE_PASSWORD: password
  ASPSP_JWTSIGNER_ALIAS: jwtsigner
  ASPSP_JWTSIGNER_KID: NTOZs+cHZSyO0p0AKPuHctl2ddc=
  CA_KEYSTORE_PATH: /secrets/ca.p12
  CA_KEYSTORE_TYPE: PKCS12
  CA_KEYSTORE_STOREPASS: Passw0rd
  CA_KEYSTORE_KEYPASS: Passw0rd
  CA_KEYSTORE_ALIAS: ca
  CA_KEK: Syz1K5XQCZtq7FkE+GNvgZPeFyvUXJdemIW7CQjM18U=
  TRUST_KEYSTORE_PATH: /secrets/ca.p12
  TRUST_KEYSTORE_TYPE: PKCS12
  TRUST_KEYSTORE_STOREPASS: Passw0rd
{{- end }}
