{{- if eq .Values.environment.type "CDK" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: obdemo.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  ENVIRONMENT_TYPE: CDK
  RS_FQDN: rs.dev.forgerock.financial
  RCS_FQDN: rcs.dev.forgerock.financial
  RCS_UI_FQDN: rcs-ui.dev.forgerock.financial
  AM_REALM: alpha 
  IG_CLIENT_ID: ig-client
  IG_CLIENT_SECRET: password
  IG_IDM_USER: service_account.ig
  IG_IDM_PASSWORD: 0penBanking!
  IG_AGENT_ID: ig-agent
  IG_AGENT_PASSWORD: password
  IG_RCS_SECRET: password
  IG_SSA_SECRET: password  
{{- end }}
